stages:
  #- lint
  - build
  - test
  - security
  - package

default:
  image: node:20-alpine

# hadolint:
#   image: hadolint/hadolint:latest
#   stage: lint
#   script:
#     - cd app
#     - hadolint Dockerfile

build_app:
  stage: build
  script:
    - cd app
    - npm ci

unit_tests:
  stage: test
  script:
    - cd app
    - npm test

sast_semgrep:
  stage: security
  image: semgrep/semgrep
  script:
    - semgrep ci --no-suppress-errors
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

secret_scan:
  stage: security
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script: 
    - gitleaks detect --source . --verbose --report-path gitleaks-report.json

sca_scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --scanners vuln --severity CRITICAL,HIGH --exit-code 1 .
  allow_failure: false

image_security:
  stage: package
  image: docker:24
  services:
    - docker:24-dind

  before_script:
    - apk add --no-cache curl tar
    - VERSION=$(curl -fsSL https://api.github.com/repos/goodwithtech/dockle/releases/latest | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
    - curl -fsSL -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
    - tar -xzf dockle.tar.gz
    - mv dockle /usr/local/bin/dockle
    - chmod +x /usr/local/bin/dockle

  script:
    - cd app
    - docker build -t devops-enigma:${CI_COMMIT_SHA} .
    - dockle --exit-code 1 --severity high devops-enigma:${CI_COMMIT_SHA}



