stages:
  - build
  - test
  - security

default:
  image: node:20-alpine

build_app:
  stage: build
  script:
    - cd app
    - npm ci

unit_tests:
  stage: test
  script:
    - cd app
    - npm test

sast_semgrep:
  stage: security
  image: semgrep/semgrep
  script:
    - semgrep ci --no-suppress-errors
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

secret_scan:
  stage: security
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script: 
    - gitleaks detect --source . --verbose --report-path gitleaks-report.json

sca_scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --scanners vuln --severity CRITICAL,HIGH --exit-code 1 .
  allow_failure: false

