stages:
  - build
  - test
  - security

default:
  image: node:20-alpine

build_app:
  stage: build
  script:
    - cd app
    - npm ci

unit_tests:
  stage: test
  script:
    - cd app
    - npm test

sast_semgrep:
  stage: security
  image: semgrep/semgrep
  script:
    - semgrep ci --no-suppress-errors
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

secret_scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - gitleaks detect --source="$CI_PROJECT_DIR" --verbose

